### ISSUE TITLE
Refactor this into a leaner meaner file

### ISSUE THREAD

**Issue by mebz** [bm14/Dev#1]
https://github.com/bm14/Dev/blob/76db8d2af3492d07d2257b981947b23ad29c5433/Codektv.html#L7

**Comment by bm14** [comment]
I shall "Bismillah"!

**Comment by mebz** [comment]
got it

**Comment by mebz** [comment]
change the alert into a console.log: 

`console.log("Lets begin by saying: Bismillah")`
